#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam?serverTimezone=GMT%2B8
    data-username: root
    data-password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  #配置jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #thymeleaf
  thymeleaf:
    cache: false

